name: SPACEL
channels:
  - conda-forge
  - defaults
dependencies:
  - cudnn=7.6.*
  - cudatoolkit=10.1.*
  - python=3.8
  - pip
  - r-base
  - r-fitdistrplus
  - pip: 
    - -r requirements.txt
    - -r docs/requirements.txt
